CREATE TABLE PRODUTO(
	ID INT NOT NULL IDENTITY(0,1) PRIMARY KEY,
	DESCRICAO VARCHAR(85) NOT NULL,
	UN INT NOT NULL,
	PRECO FLOAT NOT NULL
)

ALTER TABLE PRODUTO
ADD NOME VARCHAR(50) NOT NULL

CREATE TABLE MOVIMENTO(
	ID INT NOT NULL IDENTITY(0,1) PRIMARY KEY,
	DESCRICAO VARCHAR(85) NOT NULL,
	TIPO CHAR(1) NOT NULL,
	ID_PRODUTO INT FOREIGN KEY REFERENCES PRODUTO (ID) NOT NULL,
	QTD INT NOT NULL
)

CREATE TABLE SALDO (
	ID_PRODUTO INT FOREIGN KEY REFERENCES PRODUTO (ID) NOT NULL,
	QTD_PRODUTO INT FOREIGN KEY REFERENCES PRODUTO (ID) NOT NULL
)