CREATE OR ALTER PROCEDURE NEW_PRODUCT
	@NOME VARCHAR(50),
	@DESCRICAO VARCHAR(85),
	@UN INT,
	@PRECO FLOAT
AS
BEGIN
	INSERT INTO dbo.PRODUTOS('NOME', 'DESCRICAO', 'UN', 'PRECO')
	VALUES
	(@NOME, @DESCRICAO, @UN, @PRECO)
END